name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          project:
            - packages/interface-blockstore
            - packages/interface-blockstore-tests
            - packages/interface-datastore
            - packages/interface-datastore-tests
            - packages/interface-store
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Check deps
        run: npm run dep-check
      - uses: ipfs/aegir/actions/bundle-size@master
        name: size
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project: ${{ matrix.project }}
  test-node:
    strategy:
      matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
          project:
            - packages/interface-datastore
    needs: check
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test -- -- -- -t node --cov --bail
      - uses: codecov/codecov-action@v1
  test-chrome:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test -- -- -- -t browser -t webworker --bail
  test-firefox:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test -- -- -- -t browser -t webworker --bail -- --browser firefox
  test-electron-main:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test -- -- -- -t electron-main --bail
  test-electron-renderer:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test -- -- -- -t electron-renderer --bail
